#depl --> deployment..

apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts
  template: 
    metadata:
      labels:
        app: posts
    spec:
      containers:
      - name: posts
        image: isha7876/posts:latest #if we dont put the latest docker assumes ( by default) latest
        # ports:
        # - containerPort: 8080